<a href="https://colab.research.google.com/github/selim679/Backblaze-panne-disques-durs/blob/main/notebook33a1cab26d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

salimfekihsalem_backblaze_path = kagglehub.dataset_download('salimfekihsalem/backblaze')

print('Data source import complete.')

In [ ]:
import os
import pandas as pd
from tqdm import tqdm

DATA_DIR = "/kaggle/working/data/"
os.makedirs(DATA_DIR, exist_ok=True)

In [ ]:
def optimize_df(df):
    for col in df.columns:
        if df[col].dtype == "float64":
            df[col] = df[col].astype("float32")
        elif df[col].dtype == "int64":
            df[col] = df[col].astype("int32")
    return df

In [ ]:
def process_to_parquet_files(folders, out_dir, prefix):
    os.makedirs(out_dir, exist_ok=True)

    counter = 0

    for folder in folders:
        if not os.path.exists(folder):
            print("Missing:", folder)
            continue

        files = sorted([os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".csv")])

        print(f"\n📂 {folder} → {len(files)} files")

        for file in tqdm(files):
            try:
                df = pd.read_csv(file)
                if df.empty:
                    continue

                df = optimize_df(df)

                out_path = os.path.join(out_dir, f"{prefix}_{counter:06d}.parquet")

                df.to_parquet(out_path, engine="pyarrow", compression="snappy", index=False)

                counter += 1

            except Exception as e:
                print(f"❌ {file}: {e}")

In [ ]:
!kaggle datasets init -p /kaggle/working/data

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q1_2017 → 90 files

100%|██████████| 90/90 [02:12<00:00,  1.47s/it]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q2_2017 → 91 files

100%|██████████| 91/91 [01:41<00:00,  1.11s/it]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q3_2017 → 92 files

100%|██████████| 92/92 [01:45<00:00,  1.15s/it]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2017 → 92 files

100%|██████████| 92/92 [01:47<00:00,  1.16s/it]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2016 → 92 files

100%|██████████| 92/92 [01:24<00:00,  1.08it/s]

In [ ]:
train_files = [os.path.join(DATA_DIR + "train_2017", f) for f in os.listdir(DATA_DIR + "train_2017")]
test_files  = [os.path.join(DATA_DIR + "test_2016", f) for f in os.listdir(DATA_DIR + "test_2016")]

df_train = pd.concat([pd.read_parquet(f) for f in train_files], ignore_index=True)
df_test  = pd.concat([pd.read_parquet(f) for f in test_files], ignore_index=True)

print(df_train.shape, df_test.shape)

(30471787, 95) (6589448, 95)

In [ ]:
print("TRAIN")
print("Dimensions :", df_train.shape)
display(df_train.head())
print("\nTypes :")
print(df_train.dtypes.value_counts())
print("\nDistribution failure :")
print(df_train['failure'].value_counts())

print("\nTEST")
print("Dimensions :", df_test.shape)
display(df_test.head())

TRAIN
Dimensions : (30471787, 95)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2017-05-01,MJ0351YNG9Z0XA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,135.0,108.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-05-01,MJ0351YNG9WJSA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-05-01,PL1321LAG34XWH,Hitachi HDS5C4040ALE630,-2122489856,0,100.0,0.0,134.0,101.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-05-01,MJ0351YNGABYAA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-05-01,PL2331LAHDBJPJ,HGST HMS5C4040BLE640,-2122489856,0,100.0,0.0,133.0,104.0,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Types :
float32    58
float64    32
object      3
int32       2
Name: count, dtype: int64

Distribution failure :
failure
0    30470240
1        1547
Name: count, dtype: int64

TEST
Dimensions : (6589448, 95)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2016-11-23,MJ0351YNG9Z0XA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,135.0,108.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-11-23,MJ0351YNG9WJSA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-11-23,PL1321LAG34XWH,Hitachi HDS5C4040ALE630,-2122489856,0,100.0,0.0,134.0,101.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-11-23,MJ0351YNGABYAA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-11-23,Z305B2QN,ST4000DM000,-2122489856,0,116.0,103448624.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def analyze_columns(df):
    results = []

    for col in df.columns:
        n_unique = df[col].nunique()

        if pd.api.types.is_numeric_dtype(df[col]):
            min_val = df[col].min()
            max_val = df[col].max()
        else:
            min_val = None
            max_val = None

        results.append({
            "column": col,
            "n_unique": n_unique,
            "min": min_val,
            "max": max_val
        })

    return pd.DataFrame(results)

In [ ]:
analyze_columns(df_train)

                  column  n_unique           min           max
0                   date       364           NaN           NaN
1          serial_number    108282           NaN           NaN
2                  model        68           NaN           NaN
3         capacity_bytes        17 -2.147484e+09  1.891656e+09
4                failure         2  0.000000e+00  1.000000e+00
..                   ...       ...           ...           ...
90         smart_252_raw         1  0.000000e+00  0.000000e+00
91  smart_254_normalized         2  1.000000e+02  2.000000e+02
92         smart_254_raw         1  0.000000e+00  0.000000e+00
93  smart_255_normalized         0           NaN           NaN
94         smart_255_raw         0           NaN           NaN

[95 rows x 4 columns]

In [ ]:
def detect_constant_columns(df):
    constant_cols = []
    informative_cols = []

    for col in df.columns:
        n_unique = df[col].nunique()

        if n_unique == 1:
            constant_cols.append(col)
        else:
            if pd.api.types.is_numeric_dtype(df[col]):
                if df[col].min() == df[col].max():
                    constant_cols.append(col)
                else:
                    informative_cols.append(col)
            else:
                informative_cols.append(col)

    return constant_cols, informative_cols

In [ ]:
 detect_constant_columns(df_train)

(['smart_220_normalized',
  'smart_220_raw',
  'smart_224_normalized',
  'smart_224_raw',
  'smart_226_normalized',
  'smart_250_normalized',
  'smart_252_normalized',
  'smart_252_raw',
  'smart_254_raw'],
 ['date',
  'serial_number',
  'model',
  'capacity_bytes',
  'failure',
  'smart_1_normalized',
  'smart_1_raw',
  'smart_2_normalized',
  'smart_2_raw',
  'smart_3_normalized',
  'smart_3_raw',
  'smart_4_normalized',
  'smart_4_raw',
  'smart_5_normalized',
  'smart_5_raw',
  'smart_7_normalized',
  'smart_7_raw',
  'smart_8_normalized',
  'smart_8_raw',
  'smart_9_normalized',
  'smart_9_raw',
  'smart_10_normalized',
  'smart_10_raw',
  'smart_11_normalized',
  'smart_11_raw',
  'smart_12_normalized',
  'smart_12_raw',
  'smart_13_normalized',
  'smart_13_raw',
  'smart_15_normalized',
  'smart_15_raw',
  'smart_22_normalized',
  'smart_22_raw',
  'smart_183_normalized',
  'smart_183_raw',
  'smart_184_normalized',
  'smart_184_raw',
  'smart_187_normalized',
  'smart_187_raw',
  'smart_188_normalized',
  'smart_188_raw',
  'smart_189_normalized',
  'smart_189_raw',
  'smart_190_normalized',
  'smart_190_raw',
  'smart_191_normalized',
  'smart_191_raw',
  'smart_192_normalized',
  'smart_192_raw',
  'smart_193_normalized',
  'smart_193_raw',
  'smart_194_normalized',
  'smart_194_raw',
  'smart_195_normalized',
  'smart_195_raw',
  'smart_196_normalized',
  'smart_196_raw',
  'smart_197_normalized',
  'smart_197_raw',
  'smart_198_normalized',
  'smart_198_raw',
  'smart_199_normalized',
  'smart_199_raw',
  'smart_200_normalized',
  'smart_200_raw',
  'smart_201_normalized',
  'smart_201_raw',
  'smart_222_normalized',
  'smart_222_raw',
  'smart_223_normalized',
  'smart_223_raw',
  'smart_225_normalized',
  'smart_225_raw',
  'smart_226_raw',
  'smart_240_normalized',
  'smart_240_raw',
  'smart_241_normalized',
  'smart_241_raw',
  'smart_242_normalized',
  'smart_242_raw',
  'smart_250_raw',
  'smart_251_normalized',
  'smart_251_raw',
  'smart_254_normalized',
  'smart_255_normalized',
  'smart_255_raw'])

In [ ]:
def select_smart_columns(df, keyword="smart"):
    return [col for col in df.columns if keyword in col.lower()]

In [ ]:
select_smart_columns(df_train, keyword="smart")

['smart_1_normalized',
 'smart_1_raw',
 'smart_2_normalized',
 'smart_2_raw',
 'smart_3_normalized',
 'smart_3_raw',
 'smart_4_normalized',
 'smart_4_raw',
 'smart_5_normalized',
 'smart_5_raw',
 'smart_7_normalized',
 'smart_7_raw',
 'smart_8_normalized',
 'smart_8_raw',
 'smart_9_normalized',
 'smart_9_raw',
 'smart_10_normalized',
 'smart_10_raw',
 'smart_11_normalized',
 'smart_11_raw',
 'smart_12_normalized',
 'smart_12_raw',
 'smart_13_normalized',
 'smart_13_raw',
 'smart_15_normalized',
 'smart_15_raw',
 'smart_22_normalized',
 'smart_22_raw',
 'smart_183_normalized',
 'smart_183_raw',
 'smart_184_normalized',
 'smart_184_raw',
 'smart_187_normalized',
 'smart_187_raw',
 'smart_188_normalized',
 'smart_188_raw',
 'smart_189_normalized',
 'smart_189_raw',
 'smart_190_normalized',
 'smart_190_raw',
 'smart_191_normalized',
 'smart_191_raw',
 'smart_192_normalized',
 'smart_192_raw',
 'smart_193_normalized',
 'smart_193_raw',
 'smart_194_normalized',
 'smart_194_raw',
 'smart_195_normalized',
 'smart_195_raw',
 'smart_196_normalized',
 'smart_196_raw',
 'smart_197_normalized',
 'smart_197_raw',
 'smart_198_normalized',
 'smart_198_raw',
 'smart_199_normalized',
 'smart_199_raw',
 'smart_200_normalized',
 'smart_200_raw',
 'smart_201_normalized',
 'smart_201_raw',
 'smart_220_normalized',
 'smart_220_raw',
 'smart_222_normalized',
 'smart_222_raw',
 'smart_223_normalized',
 'smart_223_raw',
 'smart_224_normalized',
 'smart_224_raw',
 'smart_225_normalized',
 'smart_225_raw',
 'smart_226_normalized',
 'smart_226_raw',
 'smart_240_normalized',
 'smart_240_raw',
 'smart_241_normalized',
 'smart_241_raw',
 'smart_242_normalized',
 'smart_242_raw',
 'smart_250_normalized',
 'smart_250_raw',
 'smart_251_normalized',
 'smart_251_raw',
 'smart_252_normalized',
 'smart_252_raw',
 'smart_254_normalized',
 'smart_254_raw',
 'smart_255_normalized',
 'smart_255_raw']

In [ ]:
smart_cols = select_smart_columns(df_train)

df_smart = df_train[smart_cols]

constant_cols, informative_cols = detect_constant_columns(df_smart)

In [ ]:
print("Colonnes constantes :", len(constant_cols))
print("Colonnes informatives :", len(informative_cols))

In [ ]:
!kaggle datasets init -p /kaggle/working/data