<a href="https://colab.research.google.com/github/selim679/Backblaze-panne-disques-durs/blob/main/notebook33a1cab26d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

salimfekihsalem_backblaze_path = kagglehub.dataset_download('salimfekihsalem/backblaze')

print('Data source import complete.')

In [ ]:
import os
import pandas as pd
from tqdm import tqdm

DATA_DIR = "/kaggle/working/data/"
os.makedirs(DATA_DIR, exist_ok=True)

In [ ]:
def optimize_df(df):
    for col in df.columns:
        if df[col].dtype == "float64":
            df[col] = df[col].astype("float32")
        elif df[col].dtype == "int64":
            df[col] = df[col].astype("int32")
    return df

In [ ]:
def process_to_parquet_files(folders, out_dir, prefix):
    os.makedirs(out_dir, exist_ok=True)

    counter = 0

    for folder in folders:
        if not os.path.exists(folder):
            print("Missing:", folder)
            continue

        files = sorted([os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".csv")])

        print(f"\n📂 {folder} → {len(files)} files")

        for file in tqdm(files):
            try:
                df = pd.read_csv(file)
                if df.empty:
                    continue

                df = optimize_df(df)

                out_path = os.path.join(out_dir, f"{prefix}_{counter:06d}.parquet")

                df.to_parquet(out_path, engine="pyarrow", compression="snappy", index=False)

                counter += 1

            except Exception as e:
                print(f"❌ {file}: {e}")

In [ ]:
folders_2017 = [
    "/kaggle/input/datasets/salimfekihsalem/backblaze/data_Q1_2017",
    "/kaggle/input/datasets/salimfekihsalem/backblaze/data_Q2_2017",
    "/kaggle/input/datasets/salimfekihsalem/backblaze/data_Q3_2017",
    "/kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2017",
]

folders_2016_q4 = [
    "/kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2016"
]

process_to_parquet_files(folders_2017, DATA_DIR + "train_2017", "2017")
process_to_parquet_files(folders_2016_q4, DATA_DIR + "test_2016", "2016")

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q1_2017 → 90 files

100%|██████████| 90/90 [01:27<00:00,  1.03it/s]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q2_2017 → 91 files

100%|██████████| 91/91 [01:36<00:00,  1.06s/it]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q3_2017 → 92 files

100%|██████████| 92/92 [01:27<00:00,  1.05it/s]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2017 → 92 files

100%|██████████| 92/92 [01:28<00:00,  1.04it/s]

📂 /kaggle/input/datasets/salimfekihsalem/backblaze/data_Q4_2016 → 92 files

100%|██████████| 92/92 [01:10<00:00,  1.31it/s]

In [ ]:
train_files = [os.path.join(DATA_DIR + "train_2017", f) for f in os.listdir(DATA_DIR + "train_2017")]
test_files  = [os.path.join(DATA_DIR + "test_2016", f) for f in os.listdir(DATA_DIR + "test_2016")]

df_train = pd.concat([pd.read_parquet(f) for f in train_files], ignore_index=True)
df_test  = pd.concat([pd.read_parquet(f) for f in test_files], ignore_index=True)

print(df_train.shape, df_test.shape)

(30471787, 95) (6589448, 95)

In [ ]:
# ============================================================
# CELLULE 3 — Exploration rapide
# ============================================================
print("=== TRAIN ===")
print("Dimensions :", df_train.shape)
display(df_train.head())
print("\nTypes :")
print(df_train.dtypes.value_counts())
print("\nDistribution failure :")
print(df_train['failure'].value_counts())

print("\n=== TEST ===")
print("Dimensions :", df_test.shape)
display(df_test.head())

=== TRAIN ===
Dimensions : (30471787, 95)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2017-03-26,MJ0351YNG9Z0XA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,135.0,108.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-03-26,MJ0351YNG9WJSA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-03-26,PL1321LAG34XWH,Hitachi HDS5C4040ALE630,-2122489856,0,100.0,0.0,134.0,101.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-03-26,MJ0351YNGABYAA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-03-26,PL2331LAHDBJPJ,HGST HMS5C4040BLE640,-2122489856,0,100.0,0.0,133.0,104.0,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Types :
float32    58
float64    32
object      3
int32       2
Name: count, dtype: int64

Distribution failure :
failure
0    30470240
1        1547
Name: count, dtype: int64

=== TEST ===
Dimensions : (6589448, 95)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2016-12-08,MJ0351YNG9Z0XA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,135.0,108.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-12-08,MJ0351YNG9WJSA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-12-08,PL1321LAG34XWH,Hitachi HDS5C4040ALE630,-2122489856,0,100.0,0.0,134.0,101.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-12-08,MJ0351YNGABYAA,Hitachi HDS5C3030ALA630,-1589157888,0,100.0,0.0,136.0,104.0,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-12-08,Z305B2QN,ST4000DM000,-2122489856,0,117.0,120801008.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN